ALTER VIEW [SecondarySales].[vSalesDay]
AS
SELECT [DateID]
      ,[NomenclatureID]
      ,[AgentID]
      ,[TradePointID]
      ,[SalesRepresID]
      ,[SupervisorID]
      ,[SalesItem]
      ,[SalesVolume]
      ,[SalesValue]
	  ,[okb]
FROM [DWH].[SecondarySales].[SalesDay]
UNION ALL
SELECT [DateID]
      ,IDNomenclature
      ,[AgentID]
      ,[TradePointID]
      ,[SRID]
      ,[SVID]
      ,[Quantity]
      ,[SalesVolume]
      ,[Amount]
      ,[OKB]
  FROM [DWH].[SecondarySales].[vSalesChikago]
